"""auto schema update

Revision ID: 659b81107005
Revises: 001
Create Date: 2026-02-28 03:26:10.492578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
# revision identifiers, used by Alembic.
revision = '659b81107005'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_events', sa.Column('event_metadata', sa.JSON(), nullable=True))
    op.drop_column('security_events', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_events', sa.Column('metadata', sqlite.JSON(), nullable=True))
    op.drop_column('security_events', 'event_metadata')
    # ### end Alembic commands ###
